AllCops:
  TargetRubyVersion: 2.3

  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

# Disabling this as the usage of Kernel#open does not receive user's params
Security/Open:
  Enabled: false